### ISSUE TITLE
Suspend server issue...

### ISSUE THREAD

**Issue by kekshost** [death-droid/Pterodactyl-WHMCS#14]
Hello,

I can't suspend servers....I get 405 error. This is the module log:
Action: https://game-panel.kekshost.com//api/admin/servers/181/suspend
Request: 
Reponse: Array
(
    [error] => 
    [http_code] => 405
    [trace] => 
    [status_code] => 405
)

**Comment by death-droid** [comment]
It appears you are using an old version of the code, please use the latest from https://github.com/death-droid/Pterodactyl-WHMCS/blob/master/modules/servers/pterodactyl/pterodactyl.php
