### ISSUE TITLE
Servers Being Placed on the Wrong Node

### ISSUE THREAD

**Issue by AutoJukebox** [death-droid/Pterodactyl-WHMCS#16]
So, I have 3 Nodes and once I added the 3rd one all the servers get put on node #3 instead of the node that is specified in the module settings.

**Comment by death-droid** [comment]
Is autodeploy enabled? As that will override things such as the node ID from memory, I would have to double check on that

**Comment by AutoJukebox** [comment]
it was enabled, Sorry about that. I will see if that fixed the issue.

**Comment by death-droid** [comment]
Only problem i can see that might happen is that you may suddenly need to specify allocation id's, which would be painful for WHMCS as each allocation id needs to be unique.

**Comment by AutoJukebox** [comment]
It did not fix the issues. The "node id" Is it supposed to be the node name or the actual number that shows up for the node url?

**Comment by death-droid** [comment]
Is required to be a number
________________________________

**Comment by AutoJukebox** [comment]
Hmm, It is set to a number but they are always placed on node 1 and never node 2

**Comment by AutoJukebox** [comment]
Solved by making a different location for each node.
