### ISSUE TITLE
Service ID issue

### ISSUE THREAD

**Issue by fabri2000779** [death-droid/Pterodactyl-WHMCS#18]
Hello i ask on Pterodactyl discord and they told me to ask you, so my issue is this:

WHMCS Pterodactyl module works perfect but i want to change the service id from 1(Vanilla) to Spigot service but i dont know the service id, is it possible to know what is the service id, i tryed2 but nothing

**Comment by death-droid** [comment]
Service ID should be shown in the URL when going to that particular service within Pterodactyl.
