### ISSUE TITLE
Order Accept Encountered Problems 0400

### ISSUE THREAD

**Issue by hariaakash** [death-droid/Pterodactyl-WHMCS#19]
I tried accepting an order and this error showed up "Order Accept Encountered Problems" and I found that the user was created in the gpanel but it was not showing in the whmcs except the password.

**Comment by wer38** [comment]
i have the same problem

**Comment by hariaakash** [comment]
Make sure every value is set properly.

**Comment by wer38** [comment]
This is how its set im pretty sure its correct let me know if i missed anything http://prntscr.com/h14snm

**Comment by death-droid** [comment]
Ensure node is correctly setup, try setting a value for CPU usage as that may cause issues. Everything else looks right at a quick glance

**Comment by wer38** [comment]
Ok ill check that soon
