### ISSUE TITLE
Module Command Error 0400

### ISSUE THREAD

**Issue by dino147** [death-droid/Pterodactyl-WHMCS#4]
I installed the whmcs tutorial as in the module tutorial, the conexion works (at test), the module sends the command to create the username, the username is created, but the server isn't........
And I have a error: Module Command Error
0400

**Comment by dino147** [comment]
Module log:

Array
(
    [error] => Array
        (
            [service_id] => Array
                (
                    [0] => The service id field is required.
                )

        )

    [status_code] => 400
)

**Comment by hariaakash** [comment]
@dino147  can I know how you got this fixed ?
