### ISSUE TITLE
Wont connect to panel

### ISSUE THREAD

**Issue by yoshee08** [death-droid/Pterodactyl-WHMCS#5]
When I add api settings to the module, and test connection, I ALWAYS (no matter what the settings to the server, ip, or anything is) get the error "FAILED: No Nodes available, please setup a node before proceeding, otherwise this module will fail to work correctly." (and obviously I cant create a server through the whmcs)
I can set the username and password to anything, same with the domain and still get these same results. 
I have two nodes created, they work normally, are public, and yes, there is space available on them.

As I said, this message is always there no matter the settings of the ip, username/password (and yes, I have the api user/password etc put in there right now)
I've tried reinstalling the module incase something messed up. I've also restarted the daemon. There are no connection logs from what I can tell that anything even pinged the panel.

**Comment by Liq-code-ium** [comment]
I have the same issue and i would really like to get it fixed a.s.a.p.

**Comment by death-droid** [comment]
The fact your getting nothing returned hints more at a server configuration issue then an issue with the module itself. 

Until i get provided more information that can show it being an issue with this module in particular i wont be wasting my time debugging it, as it succesfully works on other systems.
