### ISSUE TITLE
WHMCS Automatic Setup Failed

### ISSUE THREAD

**Issue by dino147** [death-droid/Pterodactyl-WHMCS#6]
I have an issue, when a user pays, his account and servers is setup in the panel, and he receives the login details by email, but WHMCS recognises it as failed...
An order has received its first payment but the automatic provisioning has failed and requires you to manually check & resolve.

Client ID: 310
Service ID: 443
Product/Service: IRON
Domain:
Error: Invalid "{"language":"","fullName":" ","countryName":null}" locale.

Request log:

`Array
(
    [whmcsVersion] => 6.3.0-release.1
    [accountid] => 297
    [serviceid] => 297
    [userid] => 154
    [domain] => 
    [username] => 
    [password] => uVf412tZi3
    [packageid] => 21
    [pid] => 21
    [serverid] => 14
    [status] => Active
    [type] => other
    [producttype] => other
    [moduletype] => pterodactyl
    [configoption1] => 1512
    [configoption2] => 0
    [configoption3] => 30
    [configoption4] => 500
    [configoption5] => 4500
    [configoption6] => 1
    [configoption7] => 1
    [configoption8] => 1
    [configoption9] => 
    [configoption10] => on
    [configoption11] => 
    [configoption12] => 
    [configoption13] => 0
    [configoption14] => {{servicename}} server for user {{userid}}
    [configoption15] => 
    [configoption16] => 
    [configoption17] => 
    [configoption18] => 
    [configoption19] => 
    [configoption20] => 
    [configoption21] => 
    [configoption22] => 
    [configoption23] => 
    [configoption24] => 
    [customfields] => Array
        (
            [Email panou] => talazrobert@yahoo.com
            [Parola panou] => KeksHostEternusMC
            [Versiune server] => spigot 1.8.8
        )

    [configoptions] => Array
        (
        )

    [clientsdetails] => Array
        (
            [userid] => 154
            [id] => 154
            [uuid] => 1b822f07-4a54-48b3-898a-d69824e69ae0
            [firstname] => Robert
            [lastname] => Talaz
            [fullname] => Robert Talaz
            [companyname] => -
            [email] => talazrobert@yahoo.com
            [address1] => Sat Arini
            [address2] => Comuna Gaiceana
            [city] => Bacau
            [fullstate] => Bacau
            [state] => Bacau
            [postcode] => 0000000
            [countrycode] => RO
            [country] => RO
            [phonenumber] => 0760113658
            [password] => $2y$10$MJkubAYj8RkyWpegfcC3r.5padOu0Rgy4.mF9fwjaJlePNwZFvZsq
            [statecode] => Bacau
            [countryname] => Romania
            [phonecc] => 40
            [phonenumberformatted] => +40.760113658
            [billingcid] => 0
            [notes] => 
            [twofaenabled] => 
            [currency] => 1
            [defaultgateway] => euplatesc
            [cctype] => 
            [cclastfour] => 
            [securityqid] => 0
            [securityqans] => 
            [groupid] => 0
            [status] => Active
            [credit] => 0.00
            [taxexempt] => 
            [latefeeoveride] => 
            [overideduenotices] => 
            [separateinvoices] => 
            [disableautocc] => 
            [emailoptout] => 
            [overrideautoclose] => 
            [allowSingleSignOn] => 1
            [language] => 
            [lastlogin] => Date: 07/06/2017 15:30<br>IP Address: 109.166.132.7<br>Host: 
        )

    [server] => 1
    [serverip] => 
    [serverhostname] => https://game-panel.kekshost.com/
    [serverusername] => AECf94pA1J22iYfb
    [serverpassword] => 4roQIsE9slGJmdH9.nN0nTYF.8JBoHkV
    [serveraccesshash] => 
    [serversecure] => on
    [serverhttpprefix] => https
    [serverport] => 
    [action] => create
)
`
Response log:

`#0 /var/www/vhosts/kekshost.com/httpdocs/vendor/symfony/translation/Symfony/Component/Translation/Translator.php(247): Symfony\Component\Translation\Translator->assertValidLocale(Object(WHMCS\User\Client))
#1 /var/www/vhosts/kekshost.com/httpdocs/vendor/symfony/translation/Symfony/Component/Translation/Translator.php(210): Symfony\Component\Translation\Translator->getCatalogue(Object(WHMCS\User\Client))
#2 /var/www/vhosts/kekshost.com/httpdocs/vendor/illuminate/support/Illuminate/Support/Facades/Facade.php(217): Symfony\Component\Translation\Translator->trans('custom_field.30...', Array, 'dynamicMessages', Object(WHMCS\User\Client))
#3 /var/www/vhosts/kekshost.com/httpdocs/includes/classes/WHMCS/CustomField.php(0): Illuminate\Support\Facades\Facade::__callStatic('trans', Array)
#4 /var/www/vhosts/kekshost.com/httpdocs/includes/api/getclientsproducts.php(0): WHMCS\CustomField::getFieldName()
#5 /var/www/vhosts/kekshost.com/httpdocs/includes/functions.php(0): unknown()
#6 /var/www/vhosts/kekshost.com/httpdocs/modules/servers/pterodactyl/pterodactyl.php(381): localAPI('getclientsprodu...', Array, '1')
#7 /var/www/vhosts/kekshost.com/httpdocs/includes/classes/WHMCS/Module/AbstractModule.php(0): pterodactyl_CreateAccount(Array)
#8 /var/www/vhosts/kekshost.com/httpdocs/includes/classes/WHMCS/Module/Server.php(0): WHMCS\Module\AbstractModule->call()
#9 /var/www/vhosts/kekshost.com/httpdocs/includes/modulefunctions.php(0): WHMCS\Module\Server->call()
#10 /var/www/vhosts/kekshost.com/httpdocs/includes/modulefunctions.php(0): ModuleCallFunction()
#11 /var/www/vhosts/kekshost.com/httpdocs/admin/clientsservices.php(0): ServerCreateAccount()
#12 {main}`

**Comment by dino147** [comment]
BUMP

**Comment by death-droid** [comment]
Looks like some sort of issue with the API call, this wont be dealt with for some time.
