### ISSUE TITLE
Address already in use - Error - Install

### ISSUE THREAD

**Issue by AutoJukebox** [death-droid/Pterodactyl-WHMCS#8]
Hello, I recently installed the WHMCS module and it seems to make the server, account and send out the E-Mail without any issues but when I try to start the server it says:

 (Daemon) An error was encountered while attempting to rebuild this container.

In my Wings.log I get 

`
{"name":"wings","hostname":"ehmain","pid":1060,"level":50,"err":{"message":"(HTTP code 500) server error - driver failed programming external connectivity on endpoint 1tmtea_c86f34e8 (9a3b160ea6fe1c672527d916967fb2ee0ae5da413506b76d0fbd63af19cba6e6): Error starting userland proxy: listen udp serverip:27023: bind: address already in use ","name":"Error","stack":"Error: (HTTP code 500) server error - driver failed programming external connectivity on endpoint 1tmtea_c86f34e8 (9a3b160ea6fe1c672527d916967fb2ee0ae5da413506b76d0fbd63af19cba6e6): Error starting userland proxy: listen udp serverip:27023: bind: address already in use \n    at /mnt/eh5/srv/daemon/node_modules/docker-modem/lib/modem.js:243:17\n    at getCause (/mnt/eh5/srv/daemon/node_modules/docker-modem/lib/modem.js:273:7)\n    at Modem.buildPayload (/mnt/eh5/srv/daemon/node_modules/docker-modem/lib/modem.js:242:5)\n    at IncomingMessage.<anonymous> (/mnt/eh5/srv/daemon/node_modules/docker-modem/lib/modem.js:218:14)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},"msg":"(HTTP code 500) server error - driver failed programming external connectivity on endpoint 1tmtea_c86f34e8 (9a3b160ea6fe1c672527d916967fb2ee0ae5da413506b76d0fbd63af19cba6e6): Error starting userland proxy: listen udp serverip:27023: bind: address already in use ","time":"2017-07-14T21:25:09.921Z","v":0}`

I've done netstat | grep 27023 and nothing is running on that port.

**Comment by death-droid** [comment]
Not an issue with the WHCMS module. Pterodactyl itself handles all of that.
