### ISSUE TITLE
How exactly is this suppose to work? 

### ISSUE THREAD

**Issue by decryptedchaos** [death-droid/Pterodactyl-WHMCS#9]
I've been in IT for 20 years,  and i know my way around basic source code.   

But this module appears to be broken to me,  it's making calls to Laravel-Framework components (which do not exist in WHMCS obviously)  

Creation fails with the following PHP error.   

Fatal error: Class 'Illuminate\Database\Capsule\Manager' not found in /home/*******/public_html/billing/modules/servers/pterodactyl/pterodactyl.php on line 212

Lines 210-225

function create_user_table()
{
    if(!Capsule::schema()->hasTable('tbl_pterodactylproduct')) <--- Line 212
    {
        Capsule::schema()->create(      
            'tbl_pterodactylproduct',
            function ($table) {
                $table->increments('id');
                $table->integer('client_id');
                $table->integer('service_id');
                $table->integer('user_id');
                $table->integer('server_id');
            }
        );
    }
}

This is a Laravel Framework type calls,   and i do not see how you are exposing  these classes into the module

**Comment by death-droid** [comment]
https://developers.whmcs.com/advanced/db-interaction/

**Comment by decryptedchaos** [comment]
FYI,   This function is only available in >6.0   Which makes this module unusable by those of us on old 'owned'  licenses.
